-- MySQL Script generated by MySQL Workbench
-- Fri May 20 22:23:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phoenix_airline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phoenix_airline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phoenix_airline` DEFAULT CHARACTER SET utf8 ;
USE `phoenix_airline` ;

-- -----------------------------------------------------
-- Table `phoenix_airline`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `active_status` TINYINT NOT NULL DEFAULT 0 COMMENT '1 for active',
  `role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`session` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `user_session_id` INT NOT NULL,
  `login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `ip_address` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `user_id_idx` (`user_session_id` ASC),
  CONSTRAINT `user_session_id`
    FOREIGN KEY (`user_session_id`)
    REFERENCES `phoenix_airline`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`class` (
  `class_id` INT NOT NULL,
  `class` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`flight` (
  `flight_id` INT NOT NULL,
  `gate` VARCHAR(3) NOT NULL,
  `takeoff_airport` VARCHAR(45) NOT NULL,
  `takeoff_time` TIME NOT NULL COMMENT 'start time',
  `takeoff_date` DATE NOT NULL,
  `landing_airport` VARCHAR(45) NOT NULL,
  `landing_time` TIME NOT NULL,
  `landing_date` DATE NOT NULL,
  PRIMARY KEY (`flight_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`aircraft` (
  `aircraft_id` INT NOT NULL,
  `aircraft_brand` VARCHAR(45) NOT NULL,
  `aircraft_model` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`aircraft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`aircraft_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`aircraft_class` (
  `ac_id` INT NOT NULL,
  `aircraft_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `seats` INT NOT NULL,
  INDEX `class_id_idx` (`class_id` ASC),
  PRIMARY KEY (`ac_id`),
  CONSTRAINT `class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `phoenix_airline`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aircraft_id`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `phoenix_airline`.`aircraft` (`aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`flight_has_aircraft_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`flight_has_aircraft_class` (
  `fhac_id` INT NOT NULL,
  `flight_id` INT NOT NULL,
  `ac_id` INT NOT NULL,
  `seat_price` INT NOT NULL,
  PRIMARY KEY (`fhac_id`),
  INDEX `ac_id_idx` (`ac_id` ASC),
  INDEX `flight_id_idx` (`flight_id` ASC),
  CONSTRAINT `ac_id`
    FOREIGN KEY (`ac_id`)
    REFERENCES `phoenix_airline`.`aircraft_class` (`ac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `flight_id`
    FOREIGN KEY (`flight_id`)
    REFERENCES `phoenix_airline`.`flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phoenix_airline`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phoenix_airline`.`booking` (
  `booking_id` INT NOT NULL,
  `user_booking_id` INT NOT NULL,
  `fhac_id` INT NOT NULL,
  `passport_number` VARCHAR(15) NOT NULL,
  `booking_date` DATE NOT NULL,
  `class` VARCHAR(10) NOT NULL,
  `number_of_seats` INT NOT NULL,
  `total_price` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id_idx` (`user_booking_id` ASC),
  INDEX `fhac_id_idx` (`fhac_id` ASC),
  CONSTRAINT `user_booking_id`
    FOREIGN KEY (`user_booking_id`)
    REFERENCES `phoenix_airline`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fhac_id`
    FOREIGN KEY (`fhac_id`)
    REFERENCES `phoenix_airline`.`flight_has_aircraft_class` (`fhac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
